/* tslint:disable */
/* eslint-disable */
/*
Visier Tenant Management APIs

Visier APIs for managing tenants

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/


export * from './api/tenant-management-api';
export * from './api/tenant-management-v1-api';

