/*
Visier Tenant Management APIs

Visier APIs for managing tenants

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  TenantManagementApi,
  TenantManagementV1Api,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { VisierTenantManagementCustom } from "./client-custom";

export class VisierTenantManagement extends VisierTenantManagementCustom {
  readonly tenantManagement: TenantManagementApi;
  readonly tenantManagementV1: TenantManagementV1Api;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.tenantManagement = new TenantManagementApi(configuration);
    this.tenantManagementV1 = new TenantManagementV1Api(configuration);
  }

}
