/*
Visier Tenant Management APIs

Visier APIs for managing tenants

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TenantDetailAPIDTO } from './tenant-detail-apidto';

/**
 * 
 * @export
 * @interface AllTenantsStatusAPIDTO
 */
export interface AllTenantsStatusAPIDTO {
    /**
     * A list of objects representing all the analytic tenants.
     * @type {Array<TenantDetailAPIDTO>}
     * @memberof AllTenantsStatusAPIDTO
     */
    'tenants'?: Array<TenantDetailAPIDTO>;
    /**
     * The limit of analytic tenants to return. The maximum value is 1000.
     * @type {number}
     * @memberof AllTenantsStatusAPIDTO
     */
    'limit'?: number;
    /**
     * The index to start retrieving values from, also known as offset. The index begins at 0.
     * @type {number}
     * @memberof AllTenantsStatusAPIDTO
     */
    'start'?: number;
}

