/*
Visier Tenant Management APIs

Visier APIs for managing tenants

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The location of operations or where business is performed.
 * @export
 * @interface BusinessLocationDTO
 */
export interface BusinessLocationDTO {
    /**
     * The country in which the business is located or business is performed. The country code must follow ISO 3166 standards in alpha-2 format (two-letter code).
     * @type {string}
     * @memberof BusinessLocationDTO
     */
    'countryCode'?: string;
    /**
     * The postal code associated with the business location. Cannot be blank.
     * @type {string}
     * @memberof BusinessLocationDTO
     */
    'postalCode'?: string;
}

