/*
Visier Tenant Management APIs

Visier APIs for managing tenants

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CustomTenantPropertyDTO
 */
export interface CustomTenantPropertyDTO {
    /**
     * 
     * @type {string}
     * @memberof CustomTenantPropertyDTO
     */
    'key'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomTenantPropertyDTO
     */
    'value'?: string;
}

