/*
Visier Tenant Management APIs

Visier APIs for managing tenants

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface HomeAnalysisByUserGroupDTO
 */
export interface HomeAnalysisByUserGroupDTO {
    /**
     * The user group ID.
     * @type {string}
     * @memberof HomeAnalysisByUserGroupDTO
     */
    'userGroupId'?: string;
    /**
     * The unique ID of the analysis to show for this user group when a user logs in.
     * @type {string}
     * @memberof HomeAnalysisByUserGroupDTO
     */
    'homeAnalysisId'?: string;
}

