/*
Visier Tenant Management APIs

Visier APIs for managing tenants

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MaskMessage
 */
export interface MaskMessage {
    /**
     * A comma separated list of strings that specifies which fields to include in the response.
     * @type {string}
     * @memberof MaskMessage
     */
    'mask'?: string;
}

