/*
Visier Tenant Management APIs

Visier APIs for managing tenants

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MetricValidationSummaryDTO
 */
export interface MetricValidationSummaryDTO {
    /**
     * The symbol name of the metric. For example, \"employeeCount\".
     * @type {string}
     * @memberof MetricValidationSummaryDTO
     */
    'symbolName'?: string;
    /**
     * An identifiable name that is displayed within Visier. For example, \"Headcount\".
     * @type {string}
     * @memberof MetricValidationSummaryDTO
     */
    'displayName'?: string;
    /**
     * The current value of the metric expressed as an integer.
     * @type {number}
     * @memberof MetricValidationSummaryDTO
     */
    'value'?: number;
}

