/*
Visier Tenant Management APIs

Visier APIs for managing tenants

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ModuleSettingsDTO
 */
export interface ModuleSettingsDTO {
    /**
     * If true, the module cannot be assigned to tenants.
     * @type {boolean}
     * @memberof ModuleSettingsDTO
     */
    'unavailableForAssignment'?: boolean;
    /**
     * An instruction message in the module selection dialog. This can be a note for administrators such as \"Don\'t assign this module\" or \"Assign Module B instead\".
     * @type {string}
     * @memberof ModuleSettingsDTO
     */
    'specialHandlingInstruction'?: string;
    /**
     * The language of the module. For example, a module that is in English will have the locale \"en\".
     * @type {string}
     * @memberof ModuleSettingsDTO
     */
    'locale'?: string;
}

