/*
Visier Tenant Management APIs

Visier APIs for managing tenants

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BusinessLocationDTO } from './business-location-dto';
import { CustomPropertyDTO } from './custom-property-dto';
import { HomeAnalysisByUserGroupDTO } from './home-analysis-by-user-group-dto';

/**
 * 
 * @export
 * @interface TenantManagementAPIUpdateResponseDTO
 */
export interface TenantManagementAPIUpdateResponseDTO {
    /**
     * The unique identifier of the newly created analytic tenant.
     * @type {string}
     * @memberof TenantManagementAPIUpdateResponseDTO
     */
    'tenantCode'?: string;
    /**
     * A comma-separated collection of strings that represent the Visier modules assigned to the new analytic tenant.
     * @type {string}
     * @memberof TenantManagementAPIUpdateResponseDTO
     */
    'tenantDisplayName'?: string;
    /**
     * The 6-digit NAICS code for the industry to which the analytic tenant belongs.
     * @type {number}
     * @memberof TenantManagementAPIUpdateResponseDTO
     */
    'industryCode'?: number;
    /**
     * The primary location of operations or where business is performed. If undefined, it is omitted from the response.
     * @type {BusinessLocationDTO}
     * @memberof TenantManagementAPIUpdateResponseDTO
     */
    'primaryBusinessLocation'?: BusinessLocationDTO;
    /**
     * A comma-separated collection of strings that represent the Visier modules assigned to the new analytic tenant.
     * @type {Array<string>}
     * @memberof TenantManagementAPIUpdateResponseDTO
     */
    'purchasedModules'?: Array<string>;
    /**
     * A comma-separated list of strings that represent the URLs, or domains, in which Visier can be embedded. If domains at the administrating tenant level match the domains at the analytic tenant level, you do not need to include a domain for each analytic tenant.
     * @type {Array<string>}
     * @memberof TenantManagementAPIUpdateResponseDTO
     */
    'embeddableDomains'?: Array<string>;
    /**
     * A list of objects that represent different customizable properties for the analytic tenant.
     * @type {Array<CustomPropertyDTO>}
     * @memberof TenantManagementAPIUpdateResponseDTO
     */
    'customProperties'?: Array<CustomPropertyDTO>;
    /**
     * A comma-separated list of strings that represent the issuers for the SSO providers that can authenticate this tenant.
     * @type {Array<string>}
     * @memberof TenantManagementAPIUpdateResponseDTO
     */
    'ssoInstanceIssuers'?: Array<string>;
    /**
     * The unique ID of the analysis to display for this tenant when a user logs in. This is optional.   Retrieve the ID by opening an analysis in the production version of a tenant and copying the string after the last forward slash (/) in the URL. For example: https://jupiter.visier.com/hr/prod/appcontainer?previewId=-eZPm8xvo3SUMpD4Q5pdE-6mCj9CQ9K699XgqRGwtOxagH5x2IzDFawlWn3hYqFEfU7nP0YK9ASEzmrNfAihGg..&previewType=Production#/analytics/myanalyses/8a4c1d4f-eb61-4da0-9e5b-55bef757c30e.  The `homeAnalysisID` is 8a4c1d4f-eb61-4da0-9e5b-55bef757c30e.   Alternatively, retrieve the ID by copying the `contentId` found by following the `Embed a visualization` documentation.
     * @type {string}
     * @memberof TenantManagementAPIUpdateResponseDTO
     */
    'homeAnalysisId'?: string;
    /**
     * A list of objects representing the analysis to display to specific user groups when users log in.
     * @type {Array<HomeAnalysisByUserGroupDTO>}
     * @memberof TenantManagementAPIUpdateResponseDTO
     */
    'homeAnalysisByUserGroup'?: Array<HomeAnalysisByUserGroupDTO>;
    /**
     * Whether the tenant is enabled or disabled. Enabled tenants have access to Visier visualizations.
     * @type {string}
     * @memberof TenantManagementAPIUpdateResponseDTO
     */
    'status'?: string;
    /**
     * A custom URL to redirect users into your portal to see the relevant content. This URL is used for links that are shared by and with your users through the sharing capability or email content.
     * @type {string}
     * @memberof TenantManagementAPIUpdateResponseDTO
     */
    'clickThroughLink'?: string;
    /**
     * The name of the administrating tenant used in Visier URLs.
     * @type {string}
     * @memberof TenantManagementAPIUpdateResponseDTO
     */
    'vanityUrlName'?: string;
}

