/*
Visier Tenant Management APIs

Visier APIs for managing tenants

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BusinessLocationDTO } from './business-location-dto';
import { CustomPropertyDTO } from './custom-property-dto';
import { HomeAnalysisByUserGroupDTO } from './home-analysis-by-user-group-dto';

/**
 * 
 * @export
 * @interface TenantManagementAPIUpdateRequestDTO
 */
export interface TenantManagementAPIUpdateRequestDTO {
    /**
     * A unique identifier for the newly created analytic tenant. Required if creating new tenants.
     * @type {string}
     * @memberof TenantManagementAPIUpdateRequestDTO
     */
    'tenantCode'?: string;
    /**
     * A new display name to assign to the analytic tenant. Required if creating new tenants.
     * @type {string}
     * @memberof TenantManagementAPIUpdateRequestDTO
     */
    'tenantDisplayName'?: string;
    /**
     * A new short name to assign to the tenant. Required for Enterprise tenants
     * @type {string}
     * @memberof TenantManagementAPIUpdateRequestDTO
     */
    'tenantShortName'?: string;
    /**
     * A new vanity name to assign to the tenant. Required for Enterprise tenants
     * @type {string}
     * @memberof TenantManagementAPIUpdateRequestDTO
     */
    'vanityUrlName'?: string;
    /**
     * The 6-digit NAICS code for the industry to which the analytic tenant belongs. If the code is unknown, type 000000.  For 2-digit codes, add trailing zeros at the end to reach 6 digits, such as 620000. Required if creating new tenants.
     * @type {number}
     * @memberof TenantManagementAPIUpdateRequestDTO
     */
    'industryCode'?: number;
    /**
     * The primary location of operations or where business is performed. This field is optional.
     * @type {BusinessLocationDTO}
     * @memberof TenantManagementAPIUpdateRequestDTO
     */
    'primaryBusinessLocation'?: BusinessLocationDTO;
    /**
     * A comma-separated collection of strings that represent the Visier modules assigned to the new analytic tenant. Required if creating new tenants.
     * @type {Array<string>}
     * @memberof TenantManagementAPIUpdateRequestDTO
     */
    'purchasedModules'?: Array<string>;
    /**
     * A comma-separated list of strings that represent the URLs, or domains, in which Visier can be embedded. If domains at the administrating tenant level match the domains at the analytic tenant level, you do not need to include a domain for each analytic tenant. This is optional.
     * @type {Array<string>}
     * @memberof TenantManagementAPIUpdateRequestDTO
     */
    'embeddableDomains'?: Array<string>;
    /**
     * A list of objects that represent different customizable properties for the analytic tenant. This is optional.
     * @type {Array<CustomPropertyDTO>}
     * @memberof TenantManagementAPIUpdateRequestDTO
     */
    'customProperties'?: Array<CustomPropertyDTO>;
    /**
     * A comma-separated list of strings that represent the issuers for the SSO providers that can authenticate this tenant. This is optional.
     * @type {Array<string>}
     * @memberof TenantManagementAPIUpdateRequestDTO
     */
    'ssoInstanceIssuers'?: Array<string>;
    /**
     * The unique ID of the analysis to display for this tenant when a user logs in. This is optional. Causes the API request to take longer because it must publish a project to production.   Retrieve the ID by opening an analysis in the production version of a tenant and copying the string after the last forward slash (/) in the URL. For example: https://jupiter.visier.com/hr/prod/appcontainer?previewId=-eZPm8xvo3SUMpD4Q5pdE-6mCj9CQ9K699XgqRGwtOxagH5x2IzDFawlWn3hYqFEfU7nP0YK9ASEzmrNfAihGg..&previewType=Production#/analytics/myanalyses/8a4c1d4f-eb61-4da0-9e5b-55bef757c30e   The `homeAnalysisID` is 8a4c1d4f-eb61-4da0-9e5b-55bef757c30e. Alternatively, retrieve the ID by copying the `contentId` found by following the `Embed a visualization` documentation.
     * @type {string}
     * @memberof TenantManagementAPIUpdateRequestDTO
     */
    'homeAnalysisId'?: string;
    /**
     * A list of objects representing the analysis to display to specific user groups when users log in. This is optional. Causes the API request to take longer because it must publish a project to production.
     * @type {Array<HomeAnalysisByUserGroupDTO>}
     * @memberof TenantManagementAPIUpdateRequestDTO
     */
    'homeAnalysisByUserGroup'?: Array<HomeAnalysisByUserGroupDTO>;
    /**
     * Specifies the way you want to update values. Default is MERGE.  Valid values:  - `MERGE`: Combine the existing values with the new values.  - `REPLACE`: Remove existing values and let the new values take their place.
     * @type {string}
     * @memberof TenantManagementAPIUpdateRequestDTO
     */
    'updateAction'?: TenantManagementAPIUpdateRequestDTOUpdateActionEnum;
    /**
     * If true, the tenant is enabled. Enabled tenants have access to Visier visualizations.
     * @type {boolean}
     * @memberof TenantManagementAPIUpdateRequestDTO
     */
    'enabled'?: boolean;
    /**
     * A custom URL to redirect users into your portal to see the relevant content. This URL is used for links that are shared by and with your users through the sharing capability or email content. This is optional. Causes the API request to take longer because it must publish a project to production.
     * @type {string}
     * @memberof TenantManagementAPIUpdateRequestDTO
     */
    'clickThroughLink'?: string;
}

type TenantManagementAPIUpdateRequestDTOUpdateActionEnum = 'MERGE' | 'REPLACE'


