/*
Visier Tenant Management APIs

Visier APIs for managing tenants

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TenantStatusAPIDTO
 */
export interface TenantStatusAPIDTO {
    /**
     * The unique identifier for the analytic tenant.
     * @type {string}
     * @memberof TenantStatusAPIDTO
     */
    'tenantCode'?: string;
    /**
     * Whether the tenant is enabled or disabled.
     * @type {string}
     * @memberof TenantStatusAPIDTO
     */
    'status'?: string;
    /**
     * The identifiable tenant name that is displayed within Visier. For example, \"Callisto\".
     * @type {string}
     * @memberof TenantStatusAPIDTO
     */
    'tenantDisplayName'?: string;
    /**
     * If true, the tenant is an administrating tenant.
     * @type {boolean}
     * @memberof TenantStatusAPIDTO
     */
    'canAdministerOtherTenants'?: boolean;
}

