/*
Visier Tenant Management APIs

Visier APIs for managing tenants

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ModuleSettingsDTO } from './module-settings-dto';

/**
 * 
 * @export
 * @interface TenantModuleDTO
 */
export interface TenantModuleDTO {
    /**
     * An identifiable name that is displayed within Visier. For example, \"TALENT\".
     * @type {string}
     * @memberof TenantModuleDTO
     */
    'displayName'?: string;
    /**
     * The symbol name of the module. For example, \"Talent_Management\".
     * @type {string}
     * @memberof TenantModuleDTO
     */
    'symbolName'?: string;
    /**
     * The settings associated with the module.
     * @type {ModuleSettingsDTO}
     * @memberof TenantModuleDTO
     */
    'moduleSettings'?: ModuleSettingsDTO;
}

