/*
Visier Tenant Management APIs

Visier APIs for managing tenants

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CustomTenantPropertyDTO } from './custom-tenant-property-dto';
import { TenantModuleDTO } from './tenant-module-dto';

/**
 * 
 * @export
 * @interface TenantDetailAPIDTO
 */
export interface TenantDetailAPIDTO {
    /**
     * The tenant code of the analytic tenant. For example, \"WFF_j1r~i1o\".
     * @type {string}
     * @memberof TenantDetailAPIDTO
     */
    'tenantCode'?: string;
    /**
     * An identifiable tenant name that is displayed within Visier. For example, \"Callisto\".
     * @type {string}
     * @memberof TenantDetailAPIDTO
     */
    'tenantDisplayName'?: string;
    /**
     * Whether the tenant is enabled or disabled.
     * @type {string}
     * @memberof TenantDetailAPIDTO
     */
    'status'?: string;
    /**
     * The date that the tenant was created.
     * @type {string}
     * @memberof TenantDetailAPIDTO
     */
    'provisionDate'?: string;
    /**
     * The data version ID that the tenant is using.
     * @type {string}
     * @memberof TenantDetailAPIDTO
     */
    'currentDataVersion'?: string;
    /**
     * The date that the data version was published to production.
     * @type {string}
     * @memberof TenantDetailAPIDTO
     */
    'dataVersionDate'?: string;
    /**
     * The modules assigned to the analytic tenant.
     * @type {Array<TenantModuleDTO>}
     * @memberof TenantDetailAPIDTO
     */
    'modules'?: Array<TenantModuleDTO>;
    /**
     * The 6-digit NAICS code for the industry to which the analytic tenant belongs.
     * @type {number}
     * @memberof TenantDetailAPIDTO
     */
    'industryCode'?: number;
    /**
     * If true, the tenant is an administrating tenant.
     * @type {boolean}
     * @memberof TenantDetailAPIDTO
     */
    'canAdministerOtherTenants'?: boolean;
    /**
     * A comma-separated list of strings that represent the URLs, or domains, in which Visier can be embedded.
     * @type {Array<string>}
     * @memberof TenantDetailAPIDTO
     */
    'embeddableDomains'?: Array<string>;
    /**
     * A set of key-value pairs that represent different customizable properties for the analytic tenant.
     * @type {Array<CustomTenantPropertyDTO>}
     * @memberof TenantDetailAPIDTO
     */
    'customProperties'?: Array<CustomTenantPropertyDTO>;
    /**
     * A comma-separated list of strings that represent the issuers for the SSO providers that can authenticate this tenant.
     * @type {Array<string>}
     * @memberof TenantDetailAPIDTO
     */
    'ssoInstanceIssuers'?: Array<string>;
    /**
     * The name of the administrating tenant used in Visier URLs.
     * @type {string}
     * @memberof TenantDetailAPIDTO
     */
    'vanityUrlName'?: string;
}

