/*
Visier Tenant Management APIs

Visier APIs for managing tenants

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MetricValidationSummaryDTO } from './metric-validation-summary-dto';

/**
 * 
 * @export
 * @interface TenantPreviewEntriesSummaryDTO
 */
export interface TenantPreviewEntriesSummaryDTO {
    /**
     * The tenant code of the analytic tenant. For example, \"WFF_j1r~i1o\".
     * @type {string}
     * @memberof TenantPreviewEntriesSummaryDTO
     */
    'tenantCode'?: string;
    /**
     * The data version ID.
     * @type {string}
     * @memberof TenantPreviewEntriesSummaryDTO
     */
    'dataVersion'?: string;
    /**
     * The date that the data version was created.
     * @type {string}
     * @memberof TenantPreviewEntriesSummaryDTO
     */
    'dataVersionDate'?: string;
    /**
     * A list of metrics and their values.
     * @type {Array<MetricValidationSummaryDTO>}
     * @memberof TenantPreviewEntriesSummaryDTO
     */
    'metrics'?: Array<MetricValidationSummaryDTO>;
}

