/*
Visier Tenant Management APIs

Visier APIs for managing tenants

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TenantPreviewEntriesSummaryDTO } from './tenant-preview-entries-summary-dto';

/**
 * 
 * @export
 * @interface TenantPreviewEntriesSummaryListDTO
 */
export interface TenantPreviewEntriesSummaryListDTO {
    /**
     * A list of objects representing all the analytic tenants.
     * @type {Array<TenantPreviewEntriesSummaryDTO>}
     * @memberof TenantPreviewEntriesSummaryListDTO
     */
    'tenants'?: Array<TenantPreviewEntriesSummaryDTO>;
    /**
     * The number of analytic tenants to retrieve. The maximum number to retrieve is 1000.
     * @type {number}
     * @memberof TenantPreviewEntriesSummaryListDTO
     */
    'limit'?: number;
    /**
     * The index to start retrieving results from, also known as offset. The index begins at 0.
     * @type {number}
     * @memberof TenantPreviewEntriesSummaryListDTO
     */
    'start'?: number;
}

